id: PE2DBFFC9
initial_creation_type: ocr
source_metadata:
  volumes:
    1bce4a2cfbe2496d9d6ba0d5c74dae25:
      base_file: v077.txt
      image_group_id: I1PD95922
      title: སུམ་ཅུ་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1517
      volume_number: 77
